import { createClientFromRequest } from 'npm:@base44/sdk@0.8.44';
import { fetchBoatcastText } from '../../shared/boatcastClient.js';
const n=v=>{const x=parseFloat(String(v??'').replace(/,/g,''));return Number.isFinite(x)?x:null}; const s=v=>String(v??'').trim();
function str3(text){const ls=text.split(/\r?\n/).filter(x=>x.trim()&&x.trim()!=='data='); return ls.slice(1,7).map((l,i)=>{const p=l.split('\t'); const bb=s(p[3]).split(':'); return {boat_number:i+1,registration_number:s(p[0]),racer_name:s(p[1]).replace(/[\s　]/g,''),grade_class:s(p[5]),branch:s(bb[0]).replace(/[\s　]/g,''),age:n(p[4]),avg_st:n(p[9]),national_win_rate:n(p[10]),national_2rate:n(p[11]),national_3rate:n(p[12]),local_win_rate:n(p[13]),local_2rate:n(p[14]),local_3rate:n(p[15]),motor_number:n(p[17]),motor_2rate:n(p[18]),motor_3rate:n(p[19]),boat_number_id:n(p[21]),boat_2rate:n(p[22]),boat_3rate:n(p[23]),season_record:p.slice(25).filter(Boolean).join('|')};});}
function tkz(text){const ls=text.split(/\r?\n/).filter(x=>x.trim()&&x.trim()!=='data='); const rows=ls.filter(l=>!/^\d\t\.\d/.test(l)).slice(0,6); const st=ls.find(l=>/^\d\t\.\d/.test(l)); const sm={}; if(st){const p=st.split('\t');for(let i=0;i<p.length;i+=3)sm[Number(p[i])]=n(p[i+1]);} return rows.map((l,i)=>{const p=l.split('\t');return {boat_number:i+1,exhibition_time:n(p[1]),weight:n(p[4]),tilt:n(String(p[6]).replace(/\s/g,'')),exhibition_st:sm[i+1]??null};});}
function odds(text){const ls=text.split(/\r?\n/).filter(x=>x.trim()&&x.trim()!=='data=').slice(1,7); const out={}; for(let a=1;a<=6;a++){const p=ls[a-1]?.split('\t')||[];let k=1;for(let b=1;b<=6;b++){if(b===a)continue;for(let c=1;c<=6;c++){if(c===a||c===b)continue;const v=n(p[k++]);if(v>0)out[String(a)+'-'+String(b)+'-'+String(c)]=v;}}}return out;}
export default async function(req){try{const b=createClientFromRequest(req);const user=await b.auth.me().catch(()=>null);if(!user)return Response.json({error:'Unauthorized'},{status:401});const q=await req.json().catch(()=>({}));const date=s(q.race_date);const vc=s(q.venue_code).padStart(2,'0');const rn=Number(q.race_number);if(!date||!vc||!rn)return Response.json({error:'race_date, venue_code, race_number required'},{status:400});const sr=b.asServiceRole.entities;const races=await sr.Race.filter({race_date:date,venue_code:vc,race_number:rn},'-updated_date',1);const race=races?.[0];if(!race)return Response.json({ok:false,error:'Race not found'},{status:404});let entries=await sr.RaceEntry.filter({race_id:race.id},'boat_number',20).catch(()=>[]);const by=new Map(entries.map(e=>[Number(e.boat_number),e]));const pre=await fetchBoatcastText({type:'STR3',venueCode:vc,raceDate:date,raceNumber:rn});let preCount=0;if(pre.ok){for(const x of str3(pre.text)){const old=by.get(x.boat_number);if(old)await sr.RaceEntry.update(old.id,x);else{const z=await sr.RaceEntry.create({...x,race_id:race.id,race_date:date,venue_code:vc,race_number:rn});by.set(x.boat_number,z);}preCount++;}await sr.Race.update(race.id,{entries_fetched_at:new Date().toISOString(),last_updated:new Date().toISOString()});}
const [a,c]=await Promise.all([fetchBoatcastText({type:'TKZ',venueCode:vc,raceDate:date,raceNumber:rn}),fetchBoatcastText({type:'STT',venueCode:vc,raceDate:date,raceNumber:rn})]);let exCount=0;if(a.ok){for(const x of tkz(a.text)){const old=by.get(x.boat_number);if(old){const u={};for(const [k,v] of Object.entries(x))if(k!=='boat_number'&&v!=null)u[k]=v;await sr.RaceEntry.update(old.id,u);exCount++;}}await sr.Race.update(race.id,{exhibition_ready:exCount>=Math.max(1,6-(race.scratched_boats?.length||0)),beforeinfo_fetched_at:new Date().toISOString()});}
let od=await fetchBoatcastText({type:'ODDS',venueCode:vc,raceDate:date,raceNumber:rn,force:true});let om={};if(od.ok){om=odds(od.text);if(Object.keys(om).length){await sr.OddsSnapshot.create({race_id:race.id,race_date:date,captured_at:new Date().toISOString(),stage:'5min',all_trifecta_odds:om});await sr.Race.update(race.id,{odds_fetched_at:new Date().toISOString()});}}
return Response.json({ok:true,source:'BOATCAST',race_id:race.id,pre_race:preCount,exhibition:exCount,odds:Object.keys(om).length,stt_ok:c.ok});}catch(e){return Response.json({ok:false,error:e.message},{status:500})}}
